"""SMS delivery PORT — the interface the MFA enrollment service depends on.

An SMS MFA factor is bound by sending a one-time code to the member's verified
phone and having them enter it. Delivery is an EXTERNAL integration (an SMS
gateway / aggregator), which in the Mongolian market is an operator procurement
decision (no vendor is pinned). So the service depends on `SmsSender` (this port)
and never on a concrete gateway SDK — exactly the port+mock pattern the ХУР/XYP
eKYC integration uses. The dev/test implementation is `MockSmsSender`.

The port carries ONLY the delivery act: given a destination phone and an
already-generated code, deliver it. The code itself is generated by the service
(never by the transport), so which channel delivers it is swappable without
touching the verification logic.
"""
from __future__ import annotations

import abc


class SmsDeliveryError(Exception):
    """The SMS gateway is unreachable / rejected the message.

    Provider-neutral (no vendor pinned). The router maps it to a server-side
    delivery failure; it never carries the code.
    """


class SmsSender(abc.ABC):
    """Port: deliver a one-time verification code to a phone number."""

    @abc.abstractmethod
    def send_verification_code(self, *, phone_number: str, code: str) -> None:
        """Deliver `code` to `phone_number`, or raise `SmsDeliveryError`."""
